---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
ms.openlocfilehash: 979143e9bf95f0692c63cd68a8f0747c67a82094
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 02/17/2020
ms.locfileid: "77419700"
---
# <a name="c6320"></a>C6320

> Uyarı C6320: özel durum filtre ifadesi sabit EXCEPTION_EXECUTE_HANDLER. Bu, işlenmesi amaçlanan özel durumları maskeleyebilir

Bu uyarı, __except bloğunda EXCEPTION_EXECUTE_HANDLER sabiti kullanmanın yan etkisini gösterir. Bu durumda, belirli bir işlevde işlemek istemediğiniz özel durumlar da dahil olmak üzere \__except bloğundaki ifade her zaman özel durumu işleyecek şekilde yürütülür. Özel durumu işlemeye başlamadan önce denetlemeniz önerilir.

## <a name="example"></a>Örnek

Aşağıdaki kod bu uyarıyı oluşturur çünkü __except bloğu her türden özel durumları işlemeye çalışacaktır:

```cpp
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

Bu uyarıyı düzeltmek için, aşağıdaki kodda gösterildiği gibi, belirli bir özel durumu denetlemek için `GetExceptionCode` kullanın:

```cpp
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>Ayrıca bkz.

[try-except Deyimi](/cpp/cpp/try-except-statement)
