---
description: 'Hakkında daha fazla bilgi edinin: C6320'
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
ms.openlocfilehash: e23764d4986309e86d370be962e2e70517dd6ec7
ms.sourcegitcommit: d6af41e42699628c3e2e6063ec7b03931a49a098
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/11/2020
ms.locfileid: "97332587"
---
# <a name="c6320"></a>C6320

> Uyarı C6320: özel durum filtre ifadesi sabit EXCEPTION_EXECUTE_HANDLER. Bu, işlenmesi amaçlanan özel durumları maskeleyebilir

Bu uyarı, __except bloğunda EXCEPTION_EXECUTE_HANDLER sabiti kullanmanın yan etkisini gösterir. Bu durumda, \_ belirli bir işlevde işlemek istemediğiniz özel durumlar da dahil olmak üzere _Except bloğundaki ifade her zaman özel durumu işleyecek şekilde yürütülür. Özel durumu işlemeye başlamadan önce denetlemeniz önerilir.

## <a name="example"></a>Örnek

Aşağıdaki kod bu uyarıyı oluşturur çünkü __except bloğu her türden özel durumları işlemeye çalışacaktır:

```cpp
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

Bu uyarıyı düzeltmek için, `GetExceptionCode` aşağıdaki kodda gösterildiği gibi işlenerek belirli bir özel durumu denetlemek için kullanın:

```cpp
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>Ayrıca bkz.

[try-except ekstresi](../cpp/try-except-statement.md)
